FROM jenkins/jenkins:lts
USER root
RUN curl -sSL https://get.docker.com/ |sh
RUN usermod -g docker jenkins
RUN apt-get -y update
RUN apt-get -y upgrade \
   python3 \
   python3-dev \
   python3-pip  

USER jenkins