# docker-compose.yml
version: '3.7'
services:
  jenkins:
    privileged: true
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile_jenkins_alpine
    ports:
      - 8083:8080
      - 50003:50000
    volumes:
      - ~/docker/volumes:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock