FROM jenkins/jenkins:lts-alpine
USER root

RUN curl -sSL https://get.docker.com/ |sh
RUN usermod -g docker -G 0 jenkins

RUN apt-get -y update
RUN apt-get -y upgrade \
   sudo \
   python3 \
   python3-dev \
   python3-pip  
RUN export DOCKER_HOST=tcp://localhost:2375
RUN service docker start
USER jenkins