FROM jenkins/jenkins:lts-alpine
USER root
RUN echo 'http://dl-3.alpinelinux.org/alpine/latest-stable/community' >> /etc/apk/repositories
RUN echo 'http://dl-3.alpinelinux.org/alpine/latest-stable/main' >> /etc/apk/repositories
RUN apk add \
   curl \
   python3 \
   python3-dev \
   py3-pip \
   openrc

RUN apk update
RUN apk add docker
RUN addgroup jenkins docker
RUN rc-update add docker boot


USER jenkins