# set base image (host OS)
FROM dockerize-worker:1
USER root
RUN cat > /etc/apk/repositories << EOF; $(echo) \
http://dl-cdn.alpinelinux.org/alpine/v$(cat /etc/alpine-release | cut -d'.' -f1,2)/main \
http://dl-cdn.alpinelinux.org/alpine/v$(cat /etc/alpine-release | cut -d'.' -f1,2)/community \
EOF \
apk update 
RUN addgroup username docker
RUN apk install pylint docker
RUN rc-update add docker boot
RUN service docker start
 