# set base image (host OS)
FROM python:3.8
RUN cat > /etc/apk/repositories << EOF; $(echo) \
http://dl-cdn.alpinelinux.org/alpine/v$(cat /etc/alpine-release | cut -d'.' -f1,2)/main \
http://dl-cdn.alpinelinux.org/alpine/v$(cat /etc/alpine-release | cut -d'.' -f1,2)/community \
EOF \
apk update 
CMD ["apk", "install pylint docker"]

