pipeline {
    agent {
        dockerfile { filename 'Dockerfile.build' }
    }
    stages {
        stage('Checkout Repo') {
            steps {
                script {
                sh """git clone git@github.com:davidhullster/flask-texttool.git"""
                }
            }
        }
        stage('Install Dependencies') {
            script {
                sh """pip install -r requirements.txt"""
            }
        }
        stage('Linting') {
            script {
                sh """pylint **/*.py"""
            }
        }
        script {
          sh """ python -m unittest discover -s tests/unit"""
        }
    }
    post {
    failure {
      script {
        msg = "Build error for ${env.JOB_NAME} ${env.BUILD_NUMBER} (${env.BUILD_URL})"
            }
    }
  }
}